name: "Create a comment on new issue"

on: 
  issues:
    types: [opened]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  COMMENTS_URL: ${{ github.event.issue.comments_url }}
  ISSUE_NUMBER: ${{ github.event.issue.number }}
  OWNER: ${{ github.event.issue.user.login }}
  REPO: ${{ github.event.repository.name }}

jobs:
   Comment-with-action:
    runs-on: ubuntu-latest

    steps:
      - name: "Dump github context"
        run: | 
          echo '${{ toJSON(github.event) }}' | jq
        shell: bash

      # - name: Create comment
      #   uses: peter-evans/create-or-update-comment@v3
      #   with:
      #     issue-number: ${{ github.event.issue.number }}
      #     body: |
      #       This is a multi-line test comment
      #       - With GitHub **Markdown** :sparkles:
      #       - Created by [create-or-update-comment][1]

      #       [1]: https://github.com/peter-evans/create-or-update-comment
      #     reactions: '+1'

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v3
        id: couc
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'

      # - name: Create comment with API
      #   run: |
      #     curl -L \
      #       -X POST \
      #       -H "Accept: application/vnd.github+json" \
      #       -H "Authorization: Bearer ${GITHUB_TOKEN}"\
      #       -H "X-GitHub-Api-Version: 2022-11-28" \
      #       https://api.github.com/repos/{OWNER}/{REPO}/issues/{ISSUE_NUMBER}/comments \
      #       -d '{"body":"Me too"}'
      # /repos/OWNER/REPO/issues/ISSUE_NUMBER/comments \
      # https://api.github.com/repos/BasantPandey/LearnTerraform/issues/14/comments

      # - name: Create comment with API
      #   run: |
      #     gh api \
      #     --method POST \
      #     -H "Accept: application/vnd.github+json" \
      #     -H "X-GitHub-Api-Version: 2022-11-28" \
      #     -H "Authorization: Bearer ${GITHUB_TOKEN}"\
      #     https://api.github.com/repos/${OWNER}/${REPO}/issues/${ISSUE_NUMBER}/comments \
      #     -f body='Me too'