name: "Create a comment on new issue"

on: 
  issues:
    types: [opened]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  COMMENTS_URL: ${{ github.event.issue.comments_url }}
  NUMBER: ${{ github.event.issue.number }}

jobs:
   Comment-with-action:
    runs-on: ubuntu-latest

    steps:
      - name: "Dump github context"
        run: |
          echo 'Bearer ${GITHUB_TOKEN}'
          echo 'COMMENTS_URL ${COMMENTS_URL}'
           echo 'NUMBER ${NUMBER}'
          echo '${{ toJSON(github.event) }}' | jq
        shell: bash

      # - name: Create comment
      #   uses: peter-evans/create-or-update-comment@v1
      #   with:
      #     issue-number: ${{ github.event.issue.number }}
      #     body: |
      #       This is a multi-line test comment
      #       - With GitHub **Markdown** :sparkles:
      #     reactions: '+1'

      - name: Create comment with API
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${GITHUB_TOKEN}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            ${COMMENTS_URL} \
            -d '{"body":"Me too"}'
 