#
# Copyright (c) Microsoft Corporation
# Licensed under the MIT License.
#

name: TerraFormDeployToAzure

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - 'documentation/**'
      - '_pictures/**'
      - 'README.md'
      - 'CHANGELOG.md'
  schedule:
    - cron:  '0 3 * * *'

env:
  TF_CLI_ARGS: '-no-color'
  TF_CLI_ARGS_destroy: '-refresh=false'
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  TF_REGISTRY_DISCOVERY_RETRY: 5
  TF_REGISTRY_CLIENT_TIMEOUT: 15
  ROVER_RUNNER: true

jobs:
  foundations100:
    name: Terraform-Initialize
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
          random_length: ['5']

    container:
      image: aztfmod/rover:1.4.6-2305.1807
      options: --user 0

    steps:
      - uses: actions/checkout@v3
      
      - name: Login azure
        run: |
          az login --service-principal -u '${{ env.ARM_CLIENT_ID }}' -p '${{ env.ARM_CLIENT_SECRET }}' --tenant '${{ env.ARM_TENANT_ID }}'
          az account set -s  ${{ env.ARM_SUBSCRIPTION_ID }}
          echo "local user: $(whoami)"

      - name: Github Actions permissions workaround
        run: |
          git config --global --add safe.directory ${GITHUB_WORKSPACE}
          
      - name: Terraform Init
        run: |
            echo "Local Directory Path: ${GITHUB_WORKSPACE}"
            cd ${GITHUB_WORKSPACE}/1CAF
            terraform init
            terraform plan -out tfplan
            terraform apply -out tfplan
